name: text-to-image-generation-env

dependencies:
  - pillow
  - pytest
  - matplotlib
  - numpy
  - pandas
  - pip
  - python
  - scikit-learn
  - tensorflow-gpu
  - jupyterlab
  - opencv
  - keras
  - gdown