name: text-to-image-generation-env
# TODO: need to mention specific version numbers- check which ones we want to use
dependencies:
  - matplotlib
  - numpy
  - pandas
  - pip
  - python
  - scikit-learn
  - pytest
